export const GET_ERRORS = 'GET_ERRORS';
export const GET_RESPONSE = 'GET_RESPONSE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const BUBBLE_LOADING = 'BUBBLE_LOADING';

export const GET_BUBBLE = 'GET_BUBBLE';
export const GET_PAGE_BUBBLES = 'GET_PAGE_BUBBLES';
export const GET_USER_BUBBLES = 'GET_USER_BUBBLES';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const CREATE_BUBBLE = 'CREATE_BUBBLE';
